apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.gcp.firestore
  version: v1
  metadata:
  - name: type
    secretKeyRef:
      name: gcp-sa-access
      key: type
  - name: project_id
    secretKeyRef:
      name: gcp-sa-access
      key: project-id
  - name: private_key_id
    secretKeyRef:
      name: gcp-sa-access
      key: private-key-id
  - name: private_key
    secretKeyRef:
      name: gcp-sa-access
      key: private-key
  - name: client_email
    secretKeyRef:
      name: gcp-sa-access
      key: client-email
  - name: client_id
    secretKeyRef:
      name: gcp-sa-access
      key: client-id
  - name: auth_uri
    secretKeyRef:
      name: gcp-sa-access
      key: auth-uri
  - name: token_uri
    secretKeyRef:
      name: gcp-sa-access
      key: token-uri
  - name: auth_provider_x509_cert_url
    secretKeyRef:
      name: gcp-sa-access
      key: auth-provider-x509-cert-url
  - name: client_x509_cert_url
    secretKeyRef:
      name: gcp-sa-access
      key: client-x509-cert-url
