# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.sln .
COPY eshop/*.csproj ./eshop/
RUN dotnet restore

# copy everything else and build app
COPY eshop/. ./eshop/
WORKDIR /source/eshop
RUN dotnet publish -c release -o /App --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /App
COPY --from=build /App ./
EXPOSE 80
ENTRYPOINT ["dotnet", "eshop.dll"]
