apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.snssqs
  version: v1
  metadata:
    - name: accessKey
      secretKeyRef:
        name: aws-snssqs
        key: access-key
    - name: secretKey
      secretKeyRef:
        name: aws-snssqs
        key: secret-key
    - name: region
      secretKeyRef:
        name: aws-snssqs
        key: region
