apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: catalogdb
spec:
  type: bindings.mysql
  version: v1
  metadata:
  - name: url
    secretKeyRef:
      name: catalog-mysql
      key: url
